services:
  bot:
    build: ./bot/.
    ports:
      - 8081:8081
      - 5005:5005
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    env_file:
        - ./.env
  postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }
