services:
#  bot:
#    depends_on:
#      - scrapper
#    build: ./bot/.
#    ports:
#      - 8090:8090
#      - 5005:5005
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#    env_file:
#      - ./.env
#    networks:
#      - backend
#
#  scrapper:
#    depends_on:
#      - liquibase-migrations
#    build: ./scrapper/.
#    ports:
#      - 8080:8080
#      - 5006:5006
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#    env_file:
#      - ./.env
#    networks:
#      - backend
  postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend
  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=postgres
      #      - --log-level=debug
      #      - clearCheckSums
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend
volumes:
  postgresql: {}

networks:
  backend: {}
