-- liquibase formatted sql
--
-- changeset lsn03:1
-- comment remove necessary tables


drop table if exists CHAT cascade;
drop table if exists LINK cascade;
drop table if exists LINK_CHAT cascade;
drop table if exists SITE_TYPE cascade;
drop table if exists STACKOVERFLOW_ANSWER cascade;
drop table if exists GITHUB_COMMIT cascade;

CREATE TABLE CHAT
(
    CHAT_ID BIGINT NOT NULL
        CONSTRAINT CHAT_PK
            PRIMARY KEY,
    ACTIVE  BOOLEAN DEFAULT TRUE
);



CREATE TABLE LINK
(
    LINK_ID     BIGSERIAL
        CONSTRAINT LINK_PK
            PRIMARY KEY,
    URI         TEXT NOT NULL
        CONSTRAINT LINK_PK2
            UNIQUE,
    CREATED_AT  TIMESTAMP,
    LAST_UPDATE TIMESTAMP

);

CREATE TABLE LINK_CHAT
(
    LINK_ID BIGINT
        CONSTRAINT LINK_TO_USER_LINK_LINK_ID_FK REFERENCES LINK,
    CHAT_ID BIGINT
        CONSTRAINT LINK_TO_USER_USER_USER_ID_FK REFERENCES CHAT,
    CONSTRAINT LINK_CHAT_PK
        UNIQUE (LINK_ID, CHAT_ID)
);

CREATE TABLE GITHUB_COMMIT
(
    COMMIT_ID  BIGSERIAL NOT NULL PRIMARY KEY,
    LINK_ID    BIGINT    NOT NULL,
    SHA        TEXT      NOT NULL,
    AUTHOR     TEXT,
    CREATED_AT TIMESTAMP,
    MESSAGE    TEXT,
    CONSTRAINT GITHUB_COMMIT_PK UNIQUE (LINK_ID, SHA),
    FOREIGN KEY (LINK_ID) REFERENCES LINK (LINK_ID) ON DELETE CASCADE
);
CREATE TABLE STACKOVERFLOW_ANSWER
(
    LINK_ID            BIGINT REFERENCES LINK ON DELETE CASCADE,
    ANSWER_ID          BIGINT NOT NULL PRIMARY KEY,
    USER_NAME          TEXT,
    IS_ACCEPTED        BOOLEAN,
    CREATION_DATE      TIMESTAMP,
    LAST_ACTIVITY_DATE TIMESTAMP,
    LAST_EDIT_DATE     TIMESTAMP

);



