package edu.java.exception;

public enum BotExceptionType {
    LINK_NOT_FOUND_EXCEPTION,
    LIST_EMPTY_EXCEPTION,
    REPEAT_TRACK_EXCEPTION,
    USER_ALREADY_EXIST_EXCEPTION,
    USER_DOESNT_EXIST_EXCEPTION,
    INCORRECT_PARAMETERS_EXCEPTION

}
