app:
  telegram-token: ${APP_TELEGRAM_TOKEN:token}
  scrapper-base-url: ${BASE_URL:http://localhost:8080}
  retry:
#    strategy: exponential
    strategy: linear
#    strategy: constant
    max-attempts: 3
    max-delay: 5000 # ms
    start-delay: 5000 # ms
#    status-codes: [ 409, 404, 200 ]
    status-codes: [429, 500,501, 502,503]
  rate:
    count: 20
    seconds: 60
  kafka:
    using-queue: true
    partitions: 10
    replicas: 1
    topic: topic1

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  devtools:
    restart:
      enabled: false
  kafka:
    consumer:
      group-id: my-group-id
    bootstrap-servers: localhost:29091,localhost:29092,localhost:29093

springdoc:
  swagger-ui:
    path: /swagger-ui
server:
  port: ${BOT_PORT:8090 }

logging:
  config: classpath:log4j2-plain.xml
