app:
  telegram-token: ${APP_TELEGRAM_TOKEN:token}
  scrapper-base-url: ${BASE_URL:http://localhost:8080}
  retry:
#    strategy: exponential
    strategy: linear
#    strategy: constant
    max-attempts: 3
    max-delay: 5000 # ms
    start-delay: 5000 # ms
#    status-codes: [ 409, 404, 200 ]
    status-codes: [ 503 ]

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui
server:
  port: ${BOT_PORT:8090 }

logging:
  config: classpath:log4j2-plain.xml
