app:
  telegram-token: ${APP_TELEGRAM_TOKEN:token}
  scrapper-base-url: ${BASE_URL:http://localhost:8080}
  retry:
    strategy: linear # exponential, constant
    max-attempts: 3
    max-delay: 5000 # ms
    start-delay: 5000 # ms
    status-codes: [429, 500, 501, 502, 503]
  rate:
    count: 20
    seconds: 60
  kafka:
    using-queue: ${USING_QUEUE:true}
    partitions: 10
    replicas: 1
    topic: topic1
    topic-dlq: topic1_dlq
    servers: localhost:29091,localhost:29092,localhost:29093
    group-id: my-group-id

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  devtools:
    restart:
      enabled: false
  kafka:
    consumer:
      group-id: my-group-id
    bootstrap-servers: localhost:29091,localhost:29092,localhost:29093

springdoc:
  swagger-ui:
    path: /swagger-ui
server:
  port: ${BOT_PORT:8090 }

logging:
  config: classpath:log4j2-plain.xml

# Metrics
management:
  server:
    port: 8091
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  tags:
    application: ${spring.application.name}

