/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables;


import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.SiteTypeRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SiteType extends TableImpl<SiteTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SITE_TYPE</code>
     */
    public static final SiteType SITE_TYPE = new SiteType();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<SiteTypeRecord> getRecordType() {
        return SiteTypeRecord.class;
    }

    /**
     * The column <code>SITE_TYPE.SITE_TYPE_ID</code>.
     */
    public final TableField<SiteTypeRecord, Integer> SITE_TYPE_ID = createField(DSL.name("SITE_TYPE_ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>SITE_TYPE.NAME</code>.
     */
    public final TableField<SiteTypeRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private SiteType(Name alias, Table<SiteTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private SiteType(Name alias, Table<SiteTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>SITE_TYPE</code> table reference
     */
    public SiteType(String alias) {
        this(DSL.name(alias), SITE_TYPE);
    }

    /**
     * Create an aliased <code>SITE_TYPE</code> table reference
     */
    public SiteType(Name alias) {
        this(alias, SITE_TYPE);
    }

    /**
     * Create a <code>SITE_TYPE</code> table reference
     */
    public SiteType() {
        this(DSL.name("SITE_TYPE"), null);
    }

    public <O extends Record> SiteType(Table<O> child, ForeignKey<O, SiteTypeRecord> key) {
        super(child, key, SITE_TYPE);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<SiteTypeRecord, Integer> getIdentity() {
        return (Identity<SiteTypeRecord, Integer>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<SiteTypeRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    @Override
    @NotNull
    public List<UniqueKey<SiteTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_88);
    }

    @Override
    @NotNull
    public SiteType as(String alias) {
        return new SiteType(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public SiteType as(Name alias) {
        return new SiteType(alias, this);
    }

    @Override
    @NotNull
    public SiteType as(Table<?> alias) {
        return new SiteType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public SiteType rename(String name) {
        return new SiteType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public SiteType rename(Name name) {
        return new SiteType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public SiteType rename(Table<?> name) {
        return new SiteType(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
