/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SiteType implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer siteTypeId;
    private String name;

    public SiteType() {}

    public SiteType(SiteType value) {
        this.siteTypeId = value.siteTypeId;
        this.name = value.name;
    }

    @ConstructorProperties({ "siteTypeId", "name" })
    public SiteType(
        @Nullable Integer siteTypeId,
        @NotNull String name
    ) {
        this.siteTypeId = siteTypeId;
        this.name = name;
    }

    /**
     * Getter for <code>SITE_TYPE.SITE_TYPE_ID</code>.
     */
    @Nullable
    public Integer getSiteTypeId() {
        return this.siteTypeId;
    }

    /**
     * Setter for <code>SITE_TYPE.SITE_TYPE_ID</code>.
     */
    public void setSiteTypeId(@Nullable Integer siteTypeId) {
        this.siteTypeId = siteTypeId;
    }

    /**
     * Getter for <code>SITE_TYPE.NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 50)
    @NotNull
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>SITE_TYPE.NAME</code>.
     */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SiteType other = (SiteType) obj;
        if (this.siteTypeId == null) {
            if (other.siteTypeId != null)
                return false;
        }
        else if (!this.siteTypeId.equals(other.siteTypeId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.siteTypeId == null) ? 0 : this.siteTypeId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SiteType (");

        sb.append(siteTypeId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
