/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq;


import edu.java.domain.jooq.tables.Chat;
import edu.java.domain.jooq.tables.GithubCommit;
import edu.java.domain.jooq.tables.Link;
import edu.java.domain.jooq.tables.LinkChat;
import edu.java.domain.jooq.tables.StackoverflowAnswer;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>CHAT</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>GITHUB_COMMIT</code>.
     */
    public static final GithubCommit GITHUB_COMMIT = GithubCommit.GITHUB_COMMIT;

    /**
     * The table <code>LINK</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>LINK_CHAT</code>.
     */
    public static final LinkChat LINK_CHAT = LinkChat.LINK_CHAT;

    /**
     * The table <code>STACKOVERFLOW_ANSWER</code>.
     */
    public static final StackoverflowAnswer STACKOVERFLOW_ANSWER = StackoverflowAnswer.STACKOVERFLOW_ANSWER;
}
