FROM openjdk:21
COPY target/*.jar /scrapper.jar
# ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/scrapper.jar"]

